---
Name: nw-solr-search
---
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - SilverStripe\FullTextSearch\Solr\Control\ContentControllerExtension

#SilverStripe\Core\Injector\Injector:
#  SilverStripe\FullTextSearch\Solr\Forms\SearchForm:
#    class: NobrainerWeb\App\Search\SearchForm

SilverStripe\FullTextSearch\Search\FullTextSearch:
  indexes:
    - NobrainerWeb\Solr\Index\SolrIndex